{
  "language": "cpp",
  "sudo": false,
  "git": {
    "submodules": true
  },
  "addons": {
    "apt": {
      "packages": [
        "cmake",
        "libboost-test-dev"
      ]
    }  
  }
  "before_install": [

  ],
  "install": [

  ],
  "script": [
    "make test",
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}


