sudo: required
language: cpp
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_9a59b02794aa_key -iv $encrypted_9a59b02794aa_iv
  -in clone_data_id.enc -out clone_data_id -d
- eval `ssh-agent -s`
- chmod 700 clone_data_id
- ssh-add clone_data_id
- rm clone_data_id
- ssh-keyscan "redmine.laas.fr" >> ~/.ssh/known_hosts
- git clone ssh://git@redmine.laas.fr/laas/users/simon/fire-rs/fire-rs-data.git data/ &>/dev/null
- docker pull rafael1193/fire-rs-saop
- docker run -d -it --user=${USER_ID}:${GROUP_ID} --name saop -v `pwd`:/home/saop/code:z
  -v `pwd`/data:/home/saop/data:z abitmonn/firers-saop-dev
- docker exec --user=${USER_ID}:${GROUP_ID} saop /bin/sh -c "mkdir build-debug &&
  cd build-debug && cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j4"
script:
- docker exec --user=${USER_ID}:${GROUP_ID} saop /bin/bash -c
  "python3 python/fire_rs/planning/benchmark.py --elevation=flat --instance=1"
- docker exec --user=${USER_ID}:${GROUP_ID} saop /bin/bash -c
  "python3 python/fire_rs/planning/benchmark.py --elevation=flat --instance=2"
- docker exec --user=${USER_ID}:${GROUP_ID} saop /bin/bash -c
  "python3 python/fire_rs/planning/benchmark.py --elevation=flat --instance=3"
- docker exec --user=${USER_ID}:${GROUP_ID} saop /bin/bash -c
  "python3 python/fire_rs/planning/benchmark.py --elevation=flat --instance=4"
- docker exec --user=${USER_ID}:${GROUP_ID} saop /bin/bash -c
  "python3 python/fire_rs/planning/benchmark.py --elevation=flat --instance=5"
