{
  "language": "python",
  "python": [
    "3.5",
  ],
  "sudo": false,
  "git": {
    "submodules": true
  },
  "addons": {
    "apt": {
      "packages": [
        "cmake",
        "build-essential",
        "libboost-test-dev",
        "libgdal-dev"
      ]
    },
  },
  "before_install": [
    "pip3 install Cython",
  ],
  "install": [
    "pip3 install ./python",
    "mkdir build",
    "cd build",
    "cmake -DBUILD_TESTING=ON ..",
    "make",
    "cd .."
  ],
  "script": [
    "make test-cpp",
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}


